services:
  vizapi:
    build: .
    container_name: vizapi
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
      - "${DOCKER_STATIC_HOSTING}:/var/www/static"
    networks:
      - https
      - leetcode_bot_network
    command: npm start

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true
  leetcode_bot_network:
    name: ${LEETCODE_BOT_NETWORK}
    external: true
