services:
  vizapi:
    build: .
    container_name: vizapi
    restart: always
    user: ${UID}:10042
    ports:
      - ${PORT}:3000
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
      - "${DOCKER_STATIC_HOSTING}:/var/www/static"
    networks:
      - https
    command: npm start

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true
